version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - rupa_portal
    networks:
      - frontend
      - backend

  rupa_portal:
    build: ./rupa_portal
    container_name: rupa_portal
    volumes:
      - ./rupa_portal:/app
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
