FROM jasonish/suricata:6.0.15

# Télécharger et extraire les règles suricata " Emerging Threats"
RUN cd /tmp/ && \
    curl -LO https://rules.emergingthreats.net/open/suricata-6.0.8/emerging.rules.tar.gz && \
    tar -xvzf emerging.rules.tar.gz && \
    mkdir -p /etc/suricata/rules && mv rules/*.rules /etc/suricata/rules/ && \
    chmod 640 /etc/suricata/rules/*.rules && \
    rm -rf /tmp/*


# Télécharger et installer l'agent Wazuh
RUN curl -o wazuh-agent-4.9.2-1.x86_64.rpm https://packages.wazuh.com/4.x/yum/wazuh-agent-4.9.2-1.x86_64.rpm && \
    WAZUH_AGENT_NAME='suricata' rpm -ihv wazuh-agent-4.9.2-1.x86_64.rpm &&\
    rm wazuh-agent-4.9.2-1.x86_64.rpm

# Définir une variable d'environnement par défaut
ENV WAZUH_MANAGER_IP="127.0.0.1"

# Définir une variable d'environnement par défaut
ENV INT_TO_LISTEN="eth0"

# Copier le script de démarrage
COPY starter.sh /usr/local/bin/starter.sh
RUN chmod +x /usr/local/bin/starter.sh
    

# Configurer l'agent Wazuh
COPY ossec.conf /var/ossec/etc/ossec.conf

# Exposer les ports si nécessaire
EXPOSE 1514/tcp

# Commande de démarrage
ENTRYPOINT ["/usr/local/bin/starter.sh"]

# # Commande de démarrage de l'agent Wazuh et de Suricata
# CMD service wazuh-agent start && suricata -c /etc/suricata/suricata.yaml
