web:
  username: "admin"
  password: "rupamdp"

data-directory: /var/lib/evebox

database:
  type: sqlite

  # Automatically delete events older than 7 days.
  retention:
    days: 7

http:

  tls:
    # Enable or disable TLS.
    # env: EVEBOX_HTTP_TLS_ENABLED
    enabled: true

authentication:
  # Default: false
  # env: EVEBOX_AUTHENTICATION_REQUIRED
  required: true

# Event services: links that will be provided on events to link to additonal
# services.
event-services:

  # Custom service to link the rule in Scirius.
  - type: custom
    enabled: false
    name: Scirius

    # Only make available for alert types.
    event-types:
      - alert

    # URL template. All eve values can be used.
    url: https://10.16.1.179/rules/rule/{{alert.signature_id}}

  # Custom service to link to Dumpy for full packet capture.
  #
  # This one has no event-types meaning its available for all event types.
  - type: custom
    enabled: false
    name: Dumpy

    # The URL template, {{raw}} expands to the raw eve event as a JSON
    # string which is then url encoded. This format will give you a direct
    # download.
    url: "http://127.0.0.1:7000/fetch?query-type=event&event={{raw}}&spool=default"

    # Or this URL will pre-populate a download form for you.
    #url: "http://127.0.0.1:7000/?event={{raw}}"

    # Open in new window. The default is the same window.
    target: new