version: '3.9'

services:
  suricata:
    image: jasonish/suricata:6.0.15
    container_name: suricata
    hostname: suricata
    network_mode: "host"
    #restart: always
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      #SURICATA_OPTIONS: /usr/bin/suricata -c suricata.yaml -s signatures.rules -i ${INTERFACE_RESEAU}
    command: -i ${INTERFACE_RESEAU}
    volumes:
      - ./data/suricata/logs:/var/log/suricata
      - ./data/suricata/update:/var/lib/suricata/update
      - ./config/suricata/rules:/var/lib/suricata/rules
      - ./config/suricata/conf:/etc/suricata

  elk:
    image: sebp/elk:8.14.1
    container_name: elk
    hostname: elk
    ports:
      - "5601:5601" # kibana web interface
      - "9200:9200" # Elasticsearch JSON interface
      #- "9300:9300" # Elasticsearch transport interface
      #- "5044:5044" # Logstash beats interface
      - "5045:5045" # Logstash syslog interface
      #- "9600:9600" # Logstash API endpoint
    volumes:
      - ./data/elk/e_data_elasticsearch:/var/lib/elasticsearch
      - ./data/elk/l_data_logstash:/var/lib/logstash
      - ./data/suricata/logs:/var/log/rupa_suricata
      - ./data/elk/e_logs_elasticsearch:/var/log/elasticsearch
      - ./data/elk/l_logs_logstash:/var/log/logstash
      - ./data/elk/k_logs_kibana:/var/log/kibana
      - ./config/elk/e_config_elasticsearch:/etc/elasticsearch
      - ./config/elk/l_config_logstash:/etc/logstash/conf.d
      #- ./config/elk/l_config_logstash/03-local.conf:/etc/logstash/conf.d/03-input.conf
      - ./config/elk/k_config_kibana/conf:/opt/kibana/config
      - ./config/elk/k_config_kibana/lib:/var/lib/kibana  # Volume pour stocker les données persistantes de Kibana
      - ./config/elk/suricata-index-pattern.json:/tmp/suricata-index-pattern.json
    depends_on:
      - suricata
